### ISSUE TITLE
Parameters are rendered twice in the output

### ISSUE THREAD

**Issue by Utsira** [eneko/SourceDocs#53] opened 2020-05-27 13:17 UTC
## Brief Description

Each parameter gets included twice in the rendered output

## Steps to Reproduce

1. Find a method with parameters, and use Xcode's "Add documentation" shortcut to create a doc template:
1. Step 2
1. Step 3

## Environment

- **Operating System:** macOS 10.12.4
- **Xcode Version:** 9.0
- **SwiftDocs Version/SHA:** 0.1.0
- **Swift version:** 4.0

**Comment by eneko** [comment] 2020-05-27 16:27
Closed as duplicate of #54

**Closed by eneko** 2020-05-27 16:27 UTC
